apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deploy
  name: svc-nginx-deployment
spec:
  type: NodePort
  selector:
    app: nginx-deploy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

